#!/bin/bash

#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:10:00

# Make output directories
mkdir -p out_dir
mkdir -p out_figs

singularity exec docker://brainlife/mne:0.23dev python3 main.py


# Store epoch plot on product.json
cat << EOF > product.json
{
    "brainlife": [
       {
           "type": "image/png",
	         "name": "Evoked image",
           "base64": "$(base64 -w 0 out_figs/evoked_plot.png)"
       }

]
}
EOF
